version: 1.0.{build}
configuration: Release
dotnet_csproj:
  patch: true
  file: Maybe\Maybe.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: .\build.ps1
artifacts:
- path: '**\Maybe*.nupkg'
  name: nuget-push
deploy:
  provider: NuGet
  name: NuGet
  on:
    branch: master
  api_key:
    secure: N4s21dksdls5sci+5lmxc4ef6h8qQ6u1knvqGSLwSEXXXTGhjrGNbXGrHP/To6TR
  skip_symbols: true
  artifact: /Maybe.*\.nupkg/
